#!/usr/bin/env bash
#Install mysql 5.7 server on ubuntu 20.04
#https://www.youtube.com/watch?v=bJTSFMXk5AM

sudo mysql -u root -p

-- CREATE USER  IF NOT EXISTS 'holberton_user'@'localhost' IDENTIFIED BY 'projectcorrection280hbtn';
CREATE USER 'holberton_user'@'localhost'  IDENTIFIED WITH mysql_native_password BY 'projectcorrection280hbtn';
-- Make sure that holberton_user has permission to check the primary/replica status of your databases
GRANT REPLICATION SLAVE ON *.* TO 'holberton_user'@'localhost';


-- script to run msql commands
CREATE DATABASE IF NOT EXISTS tyrell_corp;
CREATE USER  IF NOT EXISTS 'holberton_user'@'localhost' IDENTIFIED BY 'projectcorrection280hbtn';
GRANT SELECT ON tyrell_corp.* TO 'holberton_user'@'localhost';

-- Creates table if not exists
CREATE TABLE IF NOT EXISTS nexus6(
	id INT,
	name VARCHAR(256) 
);


INSERT INTO `nexus6` VALUES(89,"I LOVE");


CREATE USER 'replica_user'@'%' IDENTIFIED BY 'root';
GRANT REPLICATION SLAVE ON *.* TO 'replica_user'@'%';



sudo mysql -u root -p tyrell_corp

FLUSH PRIVILEGES;

sudo  vim /etc/mysql/mysql.conf.d/mysqld.cnf

server-id = 1
log_bin = /var/log/mysql/mysql-bin.log
binlog_do_db = tyrell_corp

sudo ufw allow from 100.25.13.172 to any port 3306

#FILE AND POSITION
mysql-bin.000001 |      154

ssh-keygen -f ~/.ssh/server_key

cat ~/.ssh/server_key.pub | ssh ubuntu@100.25.13.172 "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"

sudo mysqldump -u root tyrell_corp -p > tyrell_corp.sql

scp -i  ~/.ssh/server_key tyrell_corp.sql ubuntu@100.25.13.172:/tmp/

sudo mysql -u root -p

CREATE DATABASE tyrell_corp;

sudo mysql -u root -p tyrell_corp < /tmp/tyrell_corp.sql

server-id = 2
log_bin = /var/log/mysql/mysql-bin.000001.log
binlog_do_db = tyrell_corp
relay_log = /var/log/mysql/mysql-relay-bin.log


sudo mysql -u root -p tyrell_corp

mysql> CHANGE MASTER TO
    -> MASTER_HOST='52.87.217.4',
    -> MASTER_USER='replica_user',
    -> MASTER_PASSWORD='root',
    -> MASTER_LOG_FILE='mysql-bin.000001',
    -> MASTER_LOG_POS=154;

-- Then you start slave
mysql> START SLAVE;

show slave status ;
show master status ;



